export * from './servicesSection/services';
export * from './gestionTiempo/gestionTiempo'
export * from "./adoutApis/apis"
export * from './GestionClientes/gestionClientes'
export * from './gestionRecursos/recursos'
export * from './rendimiento/rendimiento'
export * from './uso/uso'
export * from './cloudHibrida/cloudHibrida'
export * from './devops/devops'
export * from './migracioLegacy/migraciones'
export * from './saasOptimizacion/saasOptimizacion'